### ISSUE TITLE
Kudos and Thanks for the book!

### ISSUE THREAD

**Issue by kisna72** [thomasWeise/aitoa-code#1]
Just wanted to leave my best on this book. I was itching to learn the 'internals' of optimization after playing with Google Or- tools. That math (or code) behind was a black box that I wanted to understand but the books I picked up were quite too dense for someone just getting their feet wet in OR. 

As I was frustrated, I turned to github to find code samples so I could learn by myself. Then I stumbled on this book.

Thanks a lot for this book. This has been a blessing! 

Cheers!

P.S. I was able to build this - thanks to your book: https://kisna72.github.io/job-shop-scheduling-problem-javascript/

**Comment by thomasWeise** [comment]
Thank you ^_^
It makes me very happy, that the book at this early stage is already useful.
Currently, I am re-writing many of the chapters, including especially the Evolutionary Algorithm one.
There may be some temporary inconsistencies, but I am working on them.

Your project looks very cool!
It is really well done.
It makes me really happy that some of the information from my book helped you when creating this :-).
